name: checkup
'on':
  push:
    branches:
      - master
  schedule:
    - cron: 23 10 */3 * *
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      rev: ${{ steps.lsremote.outputs.rev }}
      label: ${{ steps.pulllabel.outputs.label }}
    steps:
      - id: lsremote
        run: echo >>"$GITHUB_OUTPUT" rev=$(git ls-remote -q https://github.com/upx/upx 2>/dev/null | head -n1 | sed 's/\s.*$//')
      - id: pulllabel
        run: docker pull docker.io/liftm/upx:latest && echo >>"$GITHUB_OUTPUT" label=$(docker image inspect --format '{{index .Config.Labels "de.liftm.upx-static-docker.rev"}}' docker.io/liftm/upx:latest)
  up:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.rev != needs.check.outputs.label
    steps:
      - run: "echo To do: ${{ needs.check.outputs.rev }} Have: ${{ needs.check.outputs.label }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: liftm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: liftm/upx:latest,liftm/upx:git-${{ needs.check.outputs.rev }}
          build-args: rev=${{ needs.check.outputs.rev }} 
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le
